[package]
name = "webidl-wit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.76"
indexmap = "2.1.0"
weedle = "0.12.0"
wit-parser = "0.13.0"
