[package]
name = "webidl-wit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.76"
heck = "0.4.1"
indexmap = "2.1.0"
itertools = "0.12.0"
# need https://github.com/rustwasm/weedle/pull/56
weedle = { git = "https://github.com/rustwasm/weedle.git" }
wit-parser = "0.13.0"
